server:
  port: 7070

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: admin-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRPAdminDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#  cloud:
#    gcp:
#      project-id: regal-height-378801
#      credentials:
#        scopes: https://www.googleapis.com/auth/devstorage.read_write
#
#myproject:
#  google:
#    storage:
#      bucketname: socialmediaavatar
#


